###CADASTRAR 
POST http://localhost:1234/medico/cadastrar
Content-Type: application/json

{
    "Nome": "kkk",
    "Crm": "190910",
    "Especialidade": "Clinico Geral"
}


###BUSCAR POR CRM 
GET http://localhost:1234/medico/buscar/190910



### RECUPERAR TODOS
GET http://localhost:1234/medico/listar 



### ALTERAR
PUT http://localhost:1234/medico/alterar
Content-Type: application/json

{
    "id": "5f765b373075b9335c3e01c3",
    "Nome": "Aline Kmiecik",
    "Crm": "190932",
    "Especialidade": "Geriatria"
}



###DELETAR
DELETE http://localhost:1234/medico/remover/190910