###CADASTRAR 
POST http://localhost:1234/medico/cadastrar
Content-Type: application/json

{
    "Nome": "jurema",
    "Crm": "321654321",
    "Especialidade": "Clinico Geral"
}


###BUSCAR POR CRM 
GET http://localhost:1234/medico/buscar/321654321



### RECUPERAR TODOS
GET http://localhost:1234/medico/listar 



### ALTERAR
PUT http://localhost:1234/medico/alterar
Content-Type: application/json

{
    "id": "5f765b373075b9335c3e01c3",
    "Nome": "Aline Kmiecik",
    "Crm": "321654321",
    "Especialidade": "clinico geral"
}



###DELETAR
DELETE http://localhost:1234/medico/remover/321654321